#coding:utf-8

Diagnosis = [ u"Depression",
				u"Angoisses chroniques",
				u"Fracture",
				u"Alzeimer",
				u"Arthrite",
				u"Arthrose",
				u"Troubles bipolaires",
				u"Rhume",
				u"Grippe",
				u"Bronchite",
				u"Pneumonie",
				u"Appendicite",
				u"Pharyngite",
				u"Laryngite",
				u"Bronchite",
				u"Eczema",
				u"Psoriasis",
				u"Diabete de type I",
				u"Diabete de type II",
				u"Dechirure des ligaments",
				u"Luxation",
				u"Schizophrenie",
				u"Epilespsie",
				u"Encephalite",
				u"Ulcere",
				u"Cancer",
				u"Sida",
				u"Traumatisme cranien",
				u"Aphasie",
				u"Foulure",
				u"Entorse",
				u"Phlebite",
				u"Angine",
				u"Maladie de Crohn",
				u"Intoxication alimentaire",
				u"Gastro-enterite"]