#coding:utf-8

EventDesc = [ u"Maux de tete",
			u"Jambe cassee",
			u"Bras cassee",
			u"Perte de memoire",
			u"Etourdissements",
			u"Main enflee",
			u"Nez casse",
			u"Coupure",
			u"Hemoragie",
			u"Traumatisme cranien",
			u"Evanouissements",
			u"Maux de ventre",
			u"Plaie(s) infectee(s)",
			u"Chute",
			u"Cotes douloureuses",
			u"Perte d''equilibre",
			u"Luxation de l''epaule",
			u"Luxation du genou",
			u"Convulsions",
			u"Tremblements",
			u"Fievre",
			u"Delires",
			u"Paralysie partielle",
			u"Paralysie totale",
			u"Douleurs musculaires",
			u"Angoisse",
			u"Depression",
			u"Difficulte a parler",
			u"Nausees",
			u"Brulures d''estomac",
			u"Maux de gorge",
			u"Eternuements",
			u"Vomissements",
			u"Perte d''appetit",
			u"Problemes de sommeil",
			u"Diarrhee",
			u"Constipation",
			u"Douleurs thoracique",
			u"Engourdissements",
			u"Perte de connaissance",
			u"Coma",
			u"Difficultes a avaler",
			u"Difficultes a respirer"]
			
Severite = [u'leger(es)', u'modere(es)', u'severe(s)', u'important(es)', u'']