/usr/bin/python genperson.py > base/person.sql
/usr/bin/python genDoctor.py > base/doctor.sql
/usr/bin/python genPatient.py > base/patient.sql
/usr/bin/python genNurse.py > base/nurse.sql
/usr/bin/python genDependant.py > base/dependant.sql
/usr/bin/python genRole.py > base/role.sql
/usr/bin/python genEvent.py > base/event.sql
/usr/bin/python genAction.py > base/action.sql
/usr/bin/python genReport.py > base/report.sql
/usr/bin/python genStatut.py > base/statut.sql
/usr/bin/python genDiagnosis.py > base/diagnosis.sql
/usr/bin/python genPrescription.py > base/prescription.sql
/usr/bin/python genCommand.py > base/command.sql
