#coding:utf-8

Medicaments = [ u"bicalutamide",
				u"finasteride",
				u"letrozole",
				u"acebutolol",
				u"acyclovir",
				u"alendronate monosodique",
				u"amiloride",
				u"amiodarone",
				u"amlodipine",
				u"amoxicilline",
				u"atenolol",
				u"azathioprine",
				u"azithromycine",
				u"azithromycine",
				u"bicalutamide",
				u"bisoprolol",
				u"bromazepam",
				u"carvedilol",
				u"cefprozil",
				u"cilazapril",
				u"cimetidine",
				u"ciprofloxacine",
				u"citalopram",
				u"clarithromycine",
				u"clindamycine",
				u"clonazepam",
				u"dexamethasone",
				u"diclofenac sodique",
				u"diltiazem", 
				u"domperidone", 
				u"enalapril",
				u"famciclovir",
				u"fluconazole",
				u"glyburide",
				u"hydrochlorothiazide",
				u"indapamide",
				u"levofloxacine",
				u"lisinopril",
				u"meloxicam",
				u"meloxicam",
				u"nizatidine",
				u"piroxicam",
				u"ramipril",
				u"sucralfate"]
				
Unites = [u"mg", u"g", u"dg", u"mL", u"dL", u"cL"]
Frequences = [u"une fois par jour", u"deux fois par jour", u"toutes les heures", u"trois fois par jour"]
UnitesTemps = [u"jour(s)", u"jour(s)", u"semaine(s)", u"mois", u"jour(s)", u"semaine(s)", u"mois", u"annee(s)"] 
