# coding:utf-8

pays = [u"Chine",
		u"Hong Kong",
		u"Macao",
		u"Inde",
		u"États-Unis",
		u"Porto Rico",
		u"Guam",
		u"Îles Vierges des États-Unis",
		u"Samoa américaines",
		u"Îles Mariannes du Nord",
		u"Indonésie",
		u"Brésil",
		u"Pakistan",
		u"Nigeria",
		u"Bangladesh",
		u"Russie",
		u"Japon",
		u"Mexique",
		u"Philippines",
		u"Viêt-Nam",
		u"Éthiopie",
		u"Égypte",
		u"Allemagne",
		u"Iran",
		u"Turquie",
		u"République démocratique du Congo",
		u"Thaïlande",
		u"France",
		u"Polynésie française",
		u"Nouvelle-Calédonie",
		u"Saint-Martin",
		u"Wallis-et-Futuna",
		u"Saint-Barthélemy",
		u"Saint-Pierre-et-Miquelon",
		u"Royaume-Uni",
		u"Bermudes",
		u"Îles Caïmans",
		u"Îles Turques-et-Caïques",
		u"Gibraltar",
		u"Îles Vierges britanniques",
		u"Anguilla",
		u"Sainte-Hélène, Ascension et Tristan da Cunha",
		u"Montserrat",
		u"Îles Malouines",
		u"Îles Pitcairn",
		u"Jersey (dépendance de la couronne)",
		u"Île de Man (dépendance de la couronne)",
		u"Guernesey (dépendance de la couronne)",
		u"Italie",
		u"Birmanie",
		u"Afrique du Sud",
		u"Corée du Sud",
		u"Espagne",
		u"Ukraine",
		u"Colombie",
		u"Tanzanie",
		u"Argentine",
		u"Kenya",
		u"Pologne",
		u"Algérie",
		u"Canada",
		u"Ouganda",
		u"Maroc",
		u"Soudan",
		u"Pérou",
		u"Irak",
		u"Arabie saoudite",
		u"Afghanistan",
		u"Népal",
		u"Ouzbékistan",
		u"Venezuela",
		u"Malaisie",
		u"Ghana",
		u"Yémen",
		u"Taïwan",
		u"Corée du Nord",
		u"Syrie",
		u"Mozambique",
		u"Australie",
		u"Île Norfolk",
		u"Île Christmas",
		u"Îles Cocos",
		u"Sri Lanka",
		u"Madagascar",
		u"Côte d''Ivoire",
		u"Cameroun",
		u"Roumanie",
		u"Pays-Bas",
		u"Antilles néerlandaises",
		u"Aruba",
		u"Chili",
		u"Burkina Faso",
		u"Niger",
		u"Kazakhstan",
		u"Malawi",
		u"Mali",
		u"Équateur",
		u"Cambodge",
		u"Sénégal",
		u"Guatemala",
		u"Angola",
		u"Zambie",
		u"Zimbabwe",
		u"Cuba",
		u"Rwanda",
		u"Belgique",
		u"Tunisie",
		u"Grèce",
		u"Tchad",
		u"Portugal",
		u"République tchèque",
		u"Guinée",
		u"Hongrie",
		u"Somalie",
		u"Bolivie",
		u"République dominicaine",
		u"Biélorussie",
		u"Burundi",
		u"Suède",
		u"Haïti",
		u"Bénin",
		u"Émirats arabes unis",
		u"Soudan du Sud",
		u"Azerbaïdjan",
		u"Autriche",
		u"Suisse",
		u"Honduras",
		u"Israël",
		u"Cisjordanie",
		u"Bande de Gaza",
		u"Serbie",
		u"Bulgarie",
		u"Tadjikistan",
		u"Salvador",
		u"Paraguay",
		u"Laos",
		u"Sierra Leone",
		u"Jordanie",
		u"Libye",
		u"Papouasie-Nouvelle-Guinée",
		u"Togo",
		u"Nicaragua",
		u"Danemark",
		u"Groenland",
		u"Îles Féroé",
		u"Slovaquie",
		u"Kirghizistan",
		u"Finlande",
		u"Turkménistan",
		u"Érythrée",
		u"Norvège",
		u"Géorgie",
		u"Singapour",
		u"Bosnie-Herzégovine",
		u"Croatie",
		u"République centrafricaine",
		u"Moldavie",
		u"Costa Rica",
		u"Nouvelle-Zélande",
		u"Îles Cook",
		u"Niue",
		u"Tokelau",
		u"Irlande",
		u"Liban",
		u"République du Congo",
		u"Albanie",
		u"Lituanie",
		u"Uruguay",
		u"Mauritanie",
		u"Liberia",
		u"Oman",
		u"Panama",
		u"Mongolie",
		u"Arménie",
		u"Jamaïque",
		u"Koweït",
		u"Lettonie",
		u"Lesotho",
		u"Namibie",
		u"Macédoine",
		u"Slovénie",
		u"Botswana",
		u"Gambie",
		u"Kosovo",
		u"Qatar",
		u"Guinée-Bissau",
		u"Gabon",
		u"Estonie",
		u"Maurice",
		u"Bahreïn",
		u"Swaziland",
		u"Timor oriental",
		u"Chypre",
		u"Trinité-et-Tobago",
		u"Fidji",
		u"Djibouti",
		u"Guyana",
		u"Comores",
		u"Bhoutan",
		u"Monténégro",
		u"Guinée équatoriale",
		u"Salomon",
		u"Luxembourg",
		u"Suriname",
		u"Cap-Vert",
		u"Malte",
		u"Brunei",
		u"Maldives",
		u"Islande",
		u"Bahamas",
		u"Belize",
		u"Barbade",
		u"Samoa",
		u"Vanuatu",
		u"Sao Tomé-et-Principe",
		u"Sainte-Lucie",
		u"Tonga",
		u"Saint-Vincent-et-les-Grenadines",
		u"Kiribati",
		u"Micronésie",
		u"Grenade",
		u"Seychelles",
		u"Dominique",
		u"Andorre",
		u"Antigua-et-Barbuda",
		u"Marshall",
		u"Saint-Christophe-et-Niévès",
		u"Liechtenstein",
		u"Monaco",
		u"Saint-Marin",
		u"Palaos",
		u"Nauru",
		u"Tuvalu"]
