#coding:utf-8

word_1 = [ u"Enflure",
			u"Complication",
			u"Diarrhee",
			u"Constipation",
			u"Maux de tete",
			u"Infection",
			u"Engourdissement",
			u"Maux de tete",
			u"Maux de gorge",
			u"Douleur",
			u"Desespoir",
			u"Hemoragie",
			u"Perte de memoire",
			u"Perte de connaissance",
			u"Fievre",
			u"Angoisse",
			u"Nausee",
			u"Vomissements",
			u"Depression",
			u"Maux de ventre",
			u"Brulures d''estomac",
			u"Etourdissements",
			u"Perte d''appetit",
			u"Eternuement",
			u"Douleurs thoraciques",
			u"Difficultes a dormir",
			u"Difficultes a avaler",
			u"Difficiltes a parler",
			u"Difficultes a respirer"]
			
adjWord_1 = [ u"leger(es).",
				u"modere(es).",
				u"important(es).",
				u"severe(s).",
				u"."]
			
adjPatient = [u"ok.",
			u"agite.",
			u"en douleur.",
			u"desagreable.",
			u"est deprime.",
			u"angoisse.",
			u"va tres bien.",
			u"va mieux.",
			u"a mange.",
			u"est engourdi.",
			u"delire.",
			u"dors.",
			u"dors mal."]

deviceReport = [u"Sortie imprevue",
				u"Detection de chute"]