# coding:utf-8

Specialty = [ u"Anatomo-pathologie",
				u"Anesthesiologie",
				u"Biochimie medicale",
				u"Cardiologie",
				u"Chirurgie cardiaque",
				u"Chirurgie colorectale",
				u"Chirurgie generale",
				u"Chirurgie generale oncologique",
				u"Chirurgie generale pediatrique",
				u"Chirurgie orthopedique",
				u"Chirurgie plastique",
				u"Chirurgie thoracique",
				u"Chirurgie vasculaire",
				u"Dermatologie",
				u"Endocrinologie et metabolisme",
				u"Gastroenterologie", 
				u"Genetique medicale",
				u"Geriatrie",
				u"Hematologie",
				u"Oncologie pediatrique",
				u"Immunologie clinique et allergie",
				u"Maladies infectieuses",
				u"Medecine communautaire",
				u"Medecine d''urgence",
				u"Medecine d''urgence pediatrique",
				u"Medecine de famille",
				u"Medecine de l''adolescence",
				u"Medecine de soins intensifs",
				u"Medecine du travail",
				u"Medecine interne",
				u"Medecine maternelle et foetale",
				u"Medecine neonatale et perinatale",
				u"Medecine nucleaire",
				u"Medecine physique et de readaptation",
				u"Microbiologie medicale",
				u"Nephrologie",
				u"Neurochirurgie",
				u"Neurologie",
				u"Neuropathologie",
				u"Obstetrique et gynecologie",
				u"Oncologie gynecologique",
				u"Oncologie medicale",
				u"Ophtalmologie",
				u"Oto-rhino-laryngologie",
				u"Pathologie generale",
				u"Pathologie hematologique",
				u"Pathologie judiciaire",
				u"Pediatrie",
				u"Pneumologie",
				u"Psychiatrie",
				u"Radiologie diagnostique",
				u"Radio-oncologie",
				u"Rhumatologie",
				u"Urologie"]